server:
  port: 5132

webssh:
  httpPort: 5132
  enableSocketProxy: true
  enableHttpProxy: true
  debugHttpProxy: true
spring:
  servlet:
    multipart:
      #set max file upload size
      max-file-size: 5GB
      max-request-size: 5GB
  profiles:
    active: prod
