server:
  port: 5443
  ssl:
    protocol: TLS
    enabled: true
    key-store: /app/webssh/websshDockerDefault.p12
    key-store-password: websshDocker@Admin123!
    key-store-type: PKCS12
    key-alias: springboottomcat
webssh:
  #force https for standalone webssh
  foreHttps: true
  #using container,default is 'tomcat'
  underContainer: tomcat

  #standalone will gen ssl while config note present
  genSslKeyOnStartupIfNotPresent: true