#just a place hoder,prepare for next release
#frolvlad/alpine-oraclejre8:slim
#pivotalservices/jdk8-minimal:latest
#https://www.cnblogs.com/lshan/p/10113284.html

FROM frolvlad/alpine-oraclejre8:slim

MAINTAINER foylian <ljs2342003@gmail.com>


COPY result/webssh_linux_$TARGETARCH /webssh

ENTRYPOINT ["/webssh"]
